name: "build"
on: [push, pull_request]
jobs:
  launch-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Run the notebooks
        run: |
          cd notebooks
          pip install -r requirements.txt
          pip install jupyter
          for f in *.ipynb; 
            do echo "Processing $f file...";
            jupyter nbconvert --execute --to notebook --inplace $f
            jupyter nbconvert --to script $f
            extension="${f##*.}"
            filename="${f%.*}"
            ipython $filename.py
          done
          ls -las